language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

matrix:
  include:
    - python: "3.10"
      dist: impish
      sudo: required
    - python: "3.11"
      dist: impish
      sudo: required

os:
  - linux

sudo: false

install:
  - pip install -U pip setuptools
  - python setup.py install
  - pip install coverage pytest-cov codecov

script:
  #This method of testing is deprecated and flagged for removal.
  #Per docs: use tox instead
  - python setup.py test

after_success:
  - codecov

