environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python310-x64"



install:        
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install -U setuptools"
  - "pip install coverage pytest-cov codecov"

build_script:
  - "python setup.py install"

test_script:
  - "python setup.py test"


